import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import { hezare } from "../next-persian-fonts/dohezar";
import { Toaster } from "react-hot-toast";
import ClientWrapper from "@/components/ClientWrapper";
import LayoutProvider from "@/components/LayoutProvider";

export const metadata: Metadata = {
  title: "وبسایت کاربر",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hezare.variable}  `}>
        <StyledComponentsRegistry>
          <ClientWrapper>
            <Toaster position="top-center" />
            <LayoutProvider>
              {children}
            </LayoutProvider>
          </ClientWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
